# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      # Create .env file for testing (with dummy API key)
      - name: Create .env file
        run: echo "WEATHER_API_KEY=test_key_for_ci" > .env

      - name: Install dependencies
        run: flutter pub get

      # Verify the use of 'dart format' on each commit
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Build APK for Android
      - name: Build Android APK
        run: flutter build apk --debug

      # Build web app
      - name: Build Web App
        run: flutter build web

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
