# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Create minimal .env file for builds (tests don't need this)
      - name: Create .env for build
        run: echo "WEATHER_API_KEY=ci_build_key" > .env

      # Verify the use of 'dart format' on each commit
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      # Note: Tests use dotenv.testLoad() to inject test API key, no .env file needed
      - name: Run tests
        run: flutter test

      # Build APK for Android
      - name: Build Android APK
        run: flutter build apk --debug

      # Build web app
      - name: Build Web App
        run: flutter build web

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # Upload Web build artifact
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
